version: '3.8'

services:
  web:
    build: .
    container_name: quantum_circuit_api
    ports:
      - "80:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - quantum_network

  redis:
    image: redis:6.2-alpine
    container_name: quantum_redis
    ports:
      - "6379:6379"
    networks:
      - quantum_network

networks:
  quantum_network:
    driver: bridge