apiVersion: v1
kind: Service
metadata:
  annotations:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "eks_helm"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: eks-service
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000  # Change to 8000 to match your app
  selector:
    app: eksdemo
  sessionAffinity: None
  type: LoadBalancer