name: Build and Deploy
on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed
jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo "::set-output name=VERSION::$(echo ${GITHUB_REF#refs/heads/} | sed 's/master/latest/' | sed 's/[^a-zA-Z0-9]/-/g')-$(git rev-parse --short HEAD)"
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESSE_TOKEN }}
        run: ls
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: noaa13092/quantum-circuit-simulator:${{ steps.get_version.outputs.VERSION }}
      # - name: Deploy to AWS EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_INSTANCE_PUBLIC_IP }}
      #     username: ec2-user
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       container_id=$(sudo docker ps | grep "quantum-circuit-simulator" | awk '{print $1}')
      #       if [ ! -z "$container_id" ]; then
      #           sudo docker-compose down
      #       fi
      #       sudo docker system prune -f -a
      #       sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/quantum-circuit-simulator:${{ steps.get_version.outputs.VERSION }}
      #       sudo docker-compose up -d
