name: Build and Push to ECR

on:
  workflow_dispatch:
  push:
    branches: [ eks ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build with Maven
      run: mvn clean install
      
    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        APP_NAME: ${{ secrets.APP_NAME }}
      run: |
        docker build -t $ECR_REGISTRY/$APP_NAME:${{ github.run_id }} .
        docker push $ECR_REGISTRY/$APP_NAME:${{ github.run_id }}
        # Optional: Tag also as latest
        docker tag $ECR_REGISTRY/$APP_NAME:${{ github.run_id }} $ECR_REGISTRY/$APP_NAME:latest
        docker push $ECR_REGISTRY/$APP_NAME:latest
